name: Check linting rules for decisionator react app.

on:
  pull_request:

jobs:
  lintReact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
