name: Check linting rules for decisionator react app.

on:
  push:
    branches: [ master, fixYaml ]

jobs:
  build_lint_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Install dependencies
        run: npm install ci
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            deploy_key: ${{ secrets.REACT_DEPLOY_KEY }}
            publish_dir: ./build
