name: Check linting rules for decisionator react app.

on:
  push:
    branches: [ master, fixYaml ]

jobs:
  build_lint_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: npm install ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Deploy to GH Pages
        run: |
          git config --global user.email "sell_nat@yahoo.com"
          git config --global user.name "sellnat77"
          git remote set-url origin "https://${secrets.ACTIONS_DEPLOY_ACCESS_TOKEN}@github.com/sellnat77/decisionator.git"
          npm run deploy
